### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sandeepsayone** [GravityLabs/goose#105]
pip3 install fails
`Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kiim5udg/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
SyntaxError: invalid syntax
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kiim5udg/beautifulsoup/`

**Comment by Shashi456** [comment]
I had the exact same problem , so to rectify this the easiest way is to stop using beautifulsoup since it has been termed obsolete in pypi and move over to beautifulsoup4
