### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by qstyler** [GravityLabs/goose#112]
Hi!

I'm trying to run use library, but getting an error here: ContentExtractor.scala:108

`scalaVersion := "2.12.3"`

```
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

Here's the callstack:

```
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at com.intenthq.gander.extractors.ContentExtractor$.com$intenthq$gander$extractors$ContentExtractor$$findYearMonthAndDay$1(ContentExtractor.scala:108)
	at com.intenthq.gander.extractors.ContentExtractor$.extractDateFromURL(ContentExtractor.scala:118)
	at com.intenthq.gander.Gander$$anonfun$extract$2$$anonfun$2$$anonfun$apply$1.apply(Gander.scala:32)
	at com.intenthq.gander.Gander$$anonfun$extract$2$$anonfun$2$$anonfun$apply$1.apply(Gander.scala:32)
	at scala.Option.flatMap(Option.scala:171)
	at com.intenthq.gander.Gander$$anonfun$extract$2$$anonfun$2.apply(Gander.scala:32)
	at com.intenthq.gander.Gander$$anonfun$extract$2$$anonfun$2.apply(Gander.scala:32)
	at scala.Option.orElse(Option.scala:289)
	at com.intenthq.gander.Gander$$anonfun$extract$2.apply(Gander.scala:32)
	at com.intenthq.gander.Gander$$anonfun$extract$2.apply(Gander.scala:30)
	at scala.Option.map(Option.scala:146)
	at com.intenthq.gander.Gander$.extract(Gander.scala:30)
```

**Comment by qstyler** [comment]
Sorry, wrong library  ¯\_(ツ)_/¯
